apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: aiops-playbook
  namespace: monitoring

spec:
  selector:
    matchLabels:
      app: aiops-playbook

  namespaceSelector:
    matchNames:
      - aiops

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
