apiVersion: apps/v1
kind: Deployment

metadata:
  name: aiops-playbook

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: aiops-playbook
          image: ghcr.io/adahmilly/aiops-gitops-playbook:a7a2546fd347b96c5dff3a5fe091b7e91040c3b1