apiVersion: apps/v1
kind: Deployment

metadata:
  name: aiops-playbook

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: aiops-playbook
          image: ghcr.io/adahmilly/aiops-gitops-playbook:e2643b8832a58aa540049455cdb95f1ff3b1a104
