apiVersion: apps/v1
kind: Deployment

metadata:
  name: aiops-playbook

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: aiops-playbook
          image: ghcr.io/adahmilly/aiops-gitops-playbook:dd3b22742ff5ab7c8228937815a0696f2a2c0e59
