apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: aiops

spec:
  ingressClassName: nginx

  rules:
    - host: aiops.local

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: aiops-service

                port:
                  number: 80